#!/usr/bin/env tsx
/**
 * Derives FLUX_POSTGREST_SCHEMA from flux.json and merges into .env.local.
 * No manual SQL schema editing.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { expectedPostgrestSchema, isFluxHashConfigured, readFluxProjectConfig } from "../lib/config/flux-schema";
import { loadEnvFiles } from "./lib/load-env";

const root = process.cwd();
loadEnvFiles(root);

const { hash, slug } = readFluxProjectConfig(root);

if (!isFluxHashConfigured(hash)) {
  console.error(
    `flux.json hash is still "${hash}". Run Flux init/push first, then re-run pnpm flux:schema:sync.`,
  );
  process.exit(1);
}

const schema = expectedPostgrestSchema(root);
const envLocalPath = join(root, ".env.local");
const line = `FLUX_POSTGREST_SCHEMA=${schema}`;

let content = "";
if (existsSync(envLocalPath)) {
  content = readFileSync(envLocalPath, "utf8");
  const re = /^FLUX_POSTGREST_SCHEMA=.*$/m;
  if (re.test(content)) {
    content = content.replace(re, line);
  } else {
    content = content.trimEnd() + `\n${line}\n`;
  }
} else {
  content = `# Generated by pnpm flux:schema:sync (project: ${slug})\n${line}\n`;
}

writeFileSync(envLocalPath, content, "utf8");
console.log(`Wrote ${envLocalPath}`);
console.log(`FLUX_POSTGREST_SCHEMA=${schema}`);
console.log("Restart dev server if running.");
